--
-- All SQL statements must be on a single line and end in a semicolon.
--

-- Dummy Data --
INSERT INTO dummy (created) VALUES (current_timestamp);

INSERT INTO account(email, pw, username) VALUES ('molly@books.com', '$2b$10$Y00XOZD/f5gBSpDusPUgU.iJufk6Nxx6gAoHRG8t2eHyGgoP2bK4y', 'Molly');

INSERT INTO account(email, pw, username) VALUES ('anna@books.com', '$2b$10$Y00XOZD/f5gBSpDusPUgU.G1ohpR3oQbbBHK4KzX7dU219Pv/lzze', 'Anna');

INSERT INTO mailbox(email, boxname) VALUES ('molly@books.com', 'Inbox');

INSERT INTO mailbox(email, boxname) VALUES ('molly@books.com', 'Sent');

INSERT INTO mailbox(email, boxname) VALUES ('molly@books.com', 'Trash');

INSERT INTO mailbox(email, boxname) VALUES ('anna@books.com', 'Inbox');

INSERT INTO mailbox(email, boxname) VALUES ('anna@books.com', 'Sent');

INSERT INTO mailbox(email, boxname) VALUES ('anna@books.com', 'Trash');

INSERT INTO mail(boxid, email, unread, starred) VALUES ('1','{"from":{"name":"Gabriel Attyeo","email":"gattyeo1n@craigslist.org"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-11-30T17:53:42Z","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","subject":"Self-enabling heuristic utilisation"}', TRUE, TRUE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('1','{"from":{"name":"Saul Adolphine","email":"sadolphine1o@blogtalkradio.com"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-11-29T01:52:29Z","content":"Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","subject":"Fully-configurable demand-driven website"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('1','{"from":{"name":"Gwen Boorman","email":"gboorman1p@skype.com"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-01-27T01:04:21Z","content":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","subject":"Mandatory empowering knowledge base"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('1','{"from":{"name":"Phebe Ruthven","email":"pruthven1q@wunderground.com"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2020-03-16T11:50:50Z","content":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","subject":"Synergistic national array"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('1','{"from":{"name":"Willette Alennikov","email":"walennikov27@toplist.cz"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-11-30T21:03:08Z","content":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","subject":"Versatile optimal product"}', TRUE, FALSE);

INSERT INTO mail(boxid, email, unread, starred) VALUES ('2','{"from":{"name":"Pedro Laurent","email":"plaurent1r@unicef.org"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-11-30T06:56:27Z","content":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","subject":"Ameliorated systematic data-warehouse"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('2','{"from":{"name":"Nola Burgoine","email":"nburgoine1s@mysql.com"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-11-29T14:02:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","subject":"Organic uniform approach"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('2','{"from":{"name":"Mikol Alldridge","email":"malldridge1t@yahoo.co.jp"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-06-25T10:38:37Z","content":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","subject":"Balanced radical internet solution"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('2','{"from":{"name":"Joete Roubottom","email":"jroubottom1u@shutterfly.com"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2020-08-08T12:51:35Z","content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","subject":"Automated tertiary ability"}', TRUE, FALSE);

INSERT INTO mail(boxid, email, unread, starred) VALUES ('3','{"from":{"name":"Frannie Bridle","email":"fbridle1v@sourceforge.net"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-11-30T14:43:23Z","content":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","subject":"Right-sized 3rd generation functionalities"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('3','{"from":{"name":"Kellina Kither","email":"kkither1w@army.mil"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-11-29T08:33:50Z","content":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","subject":"Programmable coherent definition"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('3','{"from":{"name":"Maressa Beche","email":"mbeche1x@liveinternet.ru"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2022-04-26T11:22:35Z","content":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","subject":"Implemented exuding implementation"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('3','{"from":{"name":"Ruperta Grzegorczyk","email":"rgrzegorczyk1y@nba.com"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2020-04-23T00:58:55Z","content":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","subject":"Team-oriented responsive archive"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('3','{"from":{"name":"Frieda Birckmann","email":"fbirckmann22@geocities.jp"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2020-01-02T00:48:16Z","content":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","subject":"Customizable grid-enabled hierarchy"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('3','{"from":{"name":"Frieda Birckmann","email":"fbirckmann22@geocities.jp"},"to":{"name":"Molly","email":"molly@books.com"},"received":"2020-01-02T00:48:16Z","content":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","subject":"Customizable grid-enabled hierarchy"}', FALSE, FALSE);

INSERT INTO mail(boxid, email, unread, starred) VALUES ('4','{"from":{"name":"Leroi Gorse","email":"lgorse1z@businessweek.com"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-11-30T21:40:57Z","content":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","subject":"Implemented methodical strategy"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('4','{"from":{"name":"Randy Carrier","email":"rcarrier20@samsung.com"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-11-29T09:53:14Z","content":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Up-sized maximized success"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('4','{"from":{"name":"Prescott Harlett","email":"pharlett21@senate.gov"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-06-06T22:28:28Z","content":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","subject":"Multi-tiered content-based portal"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('4','{"from":{"name":"Frieda Birckmann","email":"fbirckmann22@geocities.jp"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2020-01-02T00:48:16Z","content":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","subject":"Customizable grid-enabled hierarchy"}', FALSE, FALSE);

INSERT INTO mail(boxid, email, unread, starred) VALUES ('5','{"from":{"name":"Ina Crowcombe","email":"icrowcombe23@google.nl"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-11-30T04:44:03Z","content":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","subject":"Vision-oriented encompassing local area network"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('5','{"from":{"name":"Ursula Beamish","email":"ubeamish24@desdev.cn"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-11-29T17:45:53Z","content":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","subject":"Pre-emptive 24 hour task-force"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('5','{"from":{"name":"Irwinn Prydden","email":"iprydden25@so-net.ne.jp"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-04-04T04:19:11Z","content":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","subject":"Up-sized leading edge interface"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('5','{"from":{"name":"Raymund Begley","email":"rbegley26@hubpages.com"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2020-02-21T04:11:04Z","content":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.","subject":"Ergonomic intangible project"}', FALSE, FALSE);

INSERT INTO mail(boxid, email, unread, starred) VALUES ('6','{"from":{"name":"Willette Alennikov","email":"walennikov27@toplist.cz"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-11-30T21:03:08Z","content":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","subject":"Versatile optimal product"}', TRUE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('6','{"from":{"name":"Rosaleen Goodday","email":"rgoodday28@cpanel.net"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-11-29T12:06:51Z","content":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","subject":"Stand-alone coherent success"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('6','{"from":{"name":"Artie Swains","email":"aswains29@reverbnation.com"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2022-04-18T07:21:26Z","content":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","subject":"Enhanced 3rd generation instruction set"}', FALSE, FALSE);
INSERT INTO mail(boxid, email, unread, starred) VALUES ('6','{"from":{"name":"Trixie Gilfillan","email":"tgilfillan2a@bbc.co.uk"},"to":{"name":"Anna","email":"anna@books.com"},"received":"2020-09-10T00:53:30Z","content":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","subject":"Enhanced transitional implementation"}', FALSE, FALSE);

-- Populate Your Tables Here --
